# Backend https://www.netlifycms.org/docs/configuration-options/#backend
backend:
  name: git-gateway
  branch: master
  accept_roles:
    - admin
    - editor

# Publish mode https://www.netlifycms.org/docs/configuration-options/#publish-mode
publish_mode: editorial_workflow

# Media and Public Folders https://www.netlifycms.org/docs/configuration-options/#media-and-public-folders
media_folder: "/static/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads"

# Collections https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: Pens
    name: pens
    label_singular: Pen
    folder: "/content/pens"
    slug: "{{slug}}"
    summary: "{{title}} - {{subtitle}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: Title, name: title, widget: string }
      - { label: Subtitle, name: subtitle, widget: string }
      - { label: Etsy Link, name: etsyLink, widget: string }
      - { label: Description, name: body, widget: markdown }
      - { label: Thumbnail, name: thumbnail, widget: image }
      - label: Slideshow Images
        name: images
        widget: list
        fields:
          - { label: Image, name: image, widget: image }

  - label: General Settings
    name: general
    files:
      - name: "Website metadata"
        label: Meta
        format: json
        file: "/content/meta.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: SEO Description, name: content, widget: string }
          - { label: Fav Icon, name: favicon, widget: image }
          - label: Colors
            name: colors
            widget: list
            fields:
              - { label: Color Hex value, name: color, widget: string }

  - label: Components
    name: components
    files:
      - name: header
        label: Header
        format: json
        file: "/content/components/header.json"
        fields:
          - { label: "Logo", name: logo, widget: image }
          - { label: "Logo alt text", name: logoAlt, widget: string }
      - name: "footer"
        label: Footer
        format: json
        file: "/content/components/footer.json"
        fields:
          - { label: "Copyright", name: copyright, widget: string }

  - label: Main Pages
    name: main-pages
    files:
      - name: index
        label: Home Page
        format: json
        file: "/content/pages/index.json"
        fields:
          - { label: Main Heading Text, name: mainHeading, widget: string }
          - {
              label: Main Subheading Text,
              name: mainSubheading,
              widget: string,
            }
          - {
              label: Main Section Image,
              name: mainBackgroundImage,
              widget: image,
            }
          - {
              label: Main Section Image Alt Text,
              name: mainBackgroundImageAlt,
              widget: string,
            }
          - { label: Shop Heading, name: shopHeading, widget: string }
          - { label: Shop Subheading, name: shopSubheading, widget: string }
          - { label: Shop Featured Item 1, name: shopFeatured1, widget: string }
          - { label: Shop Featured Item 2, name: shopFeatured2, widget: string }
          - { label: Shop Featured Item 3, name: shopFeatured3, widget: string }
          - { label: Shop Button Text, name: shopButton, widget: string }
          - { label: About Text, name: aboutText, widget: string }
          - { label: About Image, name: aboutImage, widget: image }
          - { label: About Image Alt, name: aboutImageAlt, widget: string }
          - { label: Contact Heading, name: contactHeading, widget: string }
          - { label: Contact Phone, name: contactPhone, widget: string }
          - { label: Page SEO Title, name: metaTitle, widget: string }
          - { label: Page SEO Description, name: metaContent, widget: string }

      - name: shop
        label: Shop Page
        format: json
        file: "/content/pages/shop.json"
        fields:
          - { label: Heading, name: heading, widget: string }
          - { label: Page SEO Title, name: metaTitle, widget: string }
          - { label: Page SEO Description, name: metaContent, widget: string }

      - name: about
        label: About Page
        format: json
        file: "/content/pages/about.json"
        fields:
          - { label: Heading, name: heading, widget: string }
          - { label: subheading, name: subheading, widget: string }
          - { label: aboutText, name: aboutText, widget: string }
          - { label: aboutImage, name: aboutImage, widget: image }
          - { label: aboutImageAlt, name: aboutImageAlt, widget: string }
          - { label: Contact Heading, name: contactHeading, widget: string }
          - { label: Contact Phone, name: contactPhone, widget: string }
          - { label: Page SEO Title, name: metaTitle, widget: string }
          - { label: Page SEO Description, name: metaContent, widget: string }
