# Backend https://www.netlifycms.org/docs/configuration-options/#backend
backend:
  name: git-gateway
  branch: master
  accept_roles:
    - admin
    - editor

# Publish mode https://www.netlifycms.org/docs/configuration-options/#publish-mode
publish_mode: editorial_workflow

# Media and Public Folders https://www.netlifycms.org/docs/configuration-options/#media-and-public-folders
media_folder: "/static/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads"

# Collections https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: General Settings
    name: general
    files:
      - name: "meta"
        label: Meta
        format: json
        file: "/content/meta.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Content, name: content, widget: string }
          - { label: "Fav Icon", name: favicon, widget: image }

  - label: Components
    name: components
    files:
      - name: "header"
        label: Header
        format: json
        file: "/content/components/header.json"
        fields:
          - { label: "Logo", name: logo, widget: image }
          - { label: "Logo alt text", name: logoAlt, widget: string }

  - label: Main Pages
    name: main-pages
    files:
      - name: "index"
        label: Home Page
        format: json
        file: "/content/pages/index.json"
        fields:
          - { label: Main Heading Text, name: mainHeading, widget: string }
          - {
              label: Main Subheading Text,
              name: mainSubheading,
              widget: string,
            }
          - { label: Main Section Image, name: mainSectionImage, widget: image }
          - { label: Shop Heading, name: shopHeading, widget: string }
          - { label: Shop Subheading, name: shopSubheading, widget: string }
          - {
              label: Shop Featured Item 1 Image,
              name: shopFeatured1Image,
              widget: image,
            }
          - {
              label: Shop Featured Item 1 Title,
              name: shopFeatured1Title,
              widget: string,
            }
          - {
              label: Shop Featured Item 1 Description,
              name: shopFeatured1Description,
              widget: string,
            }
          - {
              label: Shop Featured Item 2 Image,
              name: shopFeatured2Image,
              widget: image,
            }
          - {
              label: Shop Featured Item 2 Title,
              name: shopFeatured2Title,
              widget: string,
            }
          - {
              label: Shop Featured Item 2 Description,
              name: shopFeatured2Description,
              widget: string,
            }
          - {
              label: Shop Featured Item 3 Image,
              name: shopFeatured3Image,
              widget: image,
            }
          - {
              label: Shop Featured Item 3 Title,
              name: shopFeatured3Title,
              widget: string,
            }
          - {
              label: Shop Featured Item 3 Description,
              name: shopFeatured3Description,
              widget: string,
            }
          - { label: About Text, name: aboutText, widget: string }
          - { label: About Image, name: aboutImage, widget: image }
          - { label: About Image Alt, name: aboutImageAlt, widget: string }
          - { label: Contact Heading, name: contactHeading, widget: string }
          - { label: Contact Phone, name: contactPhone, widget: string }
          - { label: Page SEO Title, name: meta.title, widget: string }
          - { label: Page SEO Description, name: meta.content, widget: string }

      - name: "shop"
        label: Shop Page
        format: json
        file: "/content/pages/shop.json"
        fields:
          - { label: Heading, name: heading, widget: string }
          - { label: Page SEO Title, name: meta.title, widget: string }
          - { label: Page SEO Description, name: meta.content, widget: string }

      - name: "about"
        label: About Page
        format: json
        file: "/content/pages/about.json"
        fields:
          - { label: Heading, name: heading, widget: string }
          - { label: subheading, name: subheading, widget: string }
          - { label: aboutText, name: aboutText, widget: string }
          - { label: aboutImage, name: aboutImage, widget: image }
          - { label: aboutImageAlt, name: aboutImageAlt, widget: string }
          - { label: Page SEO Title, name: meta.title, widget: string }
          - { label: Page SEO Description, name: meta.content, widget: string }

  - label: "Pens"
    name: "pens"
    label_singular: "Pen"
    folder: "content/pens"
    slug: "{{slug}}"
    summary: "{{title}} -- {{subtitle}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: Title, name: title, widget: string }
      - { label: Subtitle, name: subtitle, widget: string }
      - { label: Thumbnail, name: thumbnail, widget: string }
      - { label: Etsy Link, name: etsyLink, widget: string }
      - label: Images
        name: images
        widget: list
        fields:
          - { label: Image, name: image, widget: image }
      - { label: "Description", name: "description", widget: "markdown" }
